apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: okta-app-sso-okta-claim
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    app.kubernetes.io/part-of: okta-app-sso
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: okta-app-sso
spec:
  name: okta-claim
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: okta-claim
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: okta-app-sso

